apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    # 🌟 SINTAXIS CORRECTA: Grafana leerá de forma nativa la variable de entorno de Docker
    url: ${GF_DATASOURCES_PROMETHEUS_URL}
    uid: Prometheus
    isDefault: true
    editable: true
